**任务2：梯度计算和梯度下降过程任务要点：Pytorch梯度计算、随机梯度下降**
- 步骤1：学习自动求梯度原理，https://pytorch.org/tutorials/beginner/basics/autogradqs_tutorial.html
- 步骤2：学习随机梯度下降原理，https://www.cnblogs.com/BYRans/p/4700202.html
- 步骤3：使用numpy创建一个y=10*x+4+noise(0,1)的数据，其中x是0到100的范围，以0.01进行等差数列,使用pytroch定义w和b，并使用随机梯度下降，完成回归拟合。

In [1]:
import numpy as np
import torch 


In [2]:
# 产生数据
x_data = np.arange(0,1,0.01)
y_data = 10*x_data + 4 + np.random.normal(0,1,100)
x = torch.from_numpy(x_data)
y = torch.from_numpy(y_data)
w = torch.randn(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)




In [3]:
# print("x=",x)
# print("y=",y)
print("w=",w)
print("b=",b)

w= tensor([1.3141], requires_grad=True)
b= tensor([0.], requires_grad=True)


In [4]:
# 预测值
y_head = w * x + b

# loss 计算
loss = torch.mean((y_head - y)**2)

print("loss=",loss)


loss= tensor(72.9849, dtype=torch.float64, grad_fn=<MeanBackward0>)


In [5]:
# 计算梯度
loss.backward()
print(w.grad)
print(b.grad)

tensor([-9.4905])
tensor([-16.1761])


/opt/conda/lib/python3.6/site-packages/torch/autograd/__init__.py:132: UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  /pytorch/c10/cuda/CUDAFunctions.cpp:100.)
  allow_unreachable=True)  # allow_unreachable flag


In [6]:
# 更新 w,b
lr = 1e-2
w.data = w.data - lr * w.grad.data
b.data = b.data - lr * b.grad.data

In [7]:

print("w=",w)
print("b=",b)
print(w.requires_grad)
print(b.grad)

w= tensor([1.4090], requires_grad=True)
b= tensor([0.1618], requires_grad=True)
True
tensor([-16.1761])


In [8]:
# 进行30次更新：
for i in range(3000):
    y_head = w*x + b
#     print("w=",w)
#     print("b=",b)
    loss = torch.mean((y_head - y)**2)


    # 梯度归零, 因为前面已经求过一次了 ，所以可以直接清零，否则的话需要经过下面判断，
    #     if i != 0:
    w.grad.zero_()
    b.grad.zero_()
        # print("w.grad",w.grad)
        # print("b.grad",b.grad)
    #     print("x=",x)
    #     print("y=",y)
    #     print("y_=",y_head)

    # 自动求导
    loss.backward()
#     print(loss)
    # print(loss.grad_fn)
#     print("w.grad",w.grad)
#     print("b.grad",b.grad)
    # 更新参数
    lr = 1e-2
    w.data = w.data - lr * w.grad.data
    b.data = b.data - lr * b.grad.data
    if i % 10 == 0:
        print('epoch: {}, loss: {}'.format(i, loss.item()))




epoch: 0, loss: 69.51184937254087
epoch: 10, loss: 42.998359967626136
epoch: 20, loss: 27.075494991025135
epoch: 30, loss: 17.503853102992306
epoch: 40, loss: 11.741307764348448
epoch: 50, loss: 8.26345179965591
epoch: 60, loss: 6.156181413551235
epoch: 70, loss: 4.871341713538274
epoch: 80, loss: 4.080221669754194
epoch: 90, loss: 3.585693563710976
epoch: 100, loss: 3.2695428442976318
epoch: 110, loss: 3.060865691893939
epoch: 120, loss: 2.9171317580632
epoch: 130, loss: 2.8128256275416885
epoch: 140, loss: 2.7326359705845555
epoch: 150, loss: 2.6673658526838127
epoch: 160, loss: 2.61149140012904
epoch: 170, loss: 2.561686684079121
epoch: 180, loss: 2.515946972881058
epoch: 190, loss: 2.473058947416128
epoch: 200, loss: 2.432283769030256
epoch: 210, loss: 2.39316813612567
epoch: 220, loss: 2.3554301275162914
epoch: 230, loss: 2.3188901522625853
epoch: 240, loss: 2.2834315278326227
epoch: 250, loss: 2.248974935207971
epoch: 260, loss: 2.2154627069532045
epoch: 270, loss: 2.182852619343

In [9]:
print("w = ", w)
print("b = ", b)

w =  tensor([10.1122], requires_grad=True)
b =  tensor([3.7366], requires_grad=True)


**Q1:因为没有用.data导致的“非计算图叶子节点”错误**
- 回答：https://blog.csdn.net/zzhhjjjj/article/details/112912971
- 出错原因：
    - 将
        ``` python
        w.data = w.data - lr * w.grad.data
        b.data = b.data - lr * b.grad.data
        ```
      写为：
        ``` python
        w = w - lr * w.grad
        b = b - lr * b.grad
        ```
**Q2:因为没有清零梯度导致的错误**
- 回答： https://blog.csdn.net/m0_37637704/article/details/101019438