In [2]:
# task1:
import numpy as np
import torch
c = np.ones((3,3))
d = torch.from_numpy(c)  #numpy 转tens

In [3]:
d

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [7]:
# 以下是pytorch教程练习

from __future__ import print_function

# x = torch.Tensor(5, 3)  # 构造一个未初始化的5*3的矩阵
x = torch.rand(5, 3)  # 构造一个随机初始化的矩阵
x # 此处在notebook中输出x的值来查看具体的x内容


tensor([[0.5932, 0.2745, 0.1393],
        [0.3158, 0.4082, 0.8583],
        [0.2483, 0.2121, 0.5212],
        [0.0342, 0.3938, 0.7519],
        [0.8341, 0.0197, 0.7007]])

In [8]:
x.size()

torch.Size([5, 3])

In [9]:
y = torch.rand(5,3)

In [10]:
# x + y
torch.add(x,y)

tensor([[1.2007, 1.0333, 0.5155],
        [0.5010, 1.1400, 1.1297],
        [0.9740, 0.5760, 0.9672],
        [0.8308, 1.2873, 1.5206],
        [1.4619, 0.5044, 1.4087]])

In [11]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    x = x.to(device)
    y = y.to(device)
    z = x+y
    print(z)
    print(z.to("cpu", torch.double))

/opt/conda/lib/python3.6/site-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  /pytorch/c10/cuda/CUDAFunctions.cpp:100.)
  return torch._C._cuda_getDeviceCount() > 0


In [12]:
x = torch.ones(2,2,requires_grad=True)

In [13]:
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [14]:
y = x+2

In [15]:
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [16]:
y.grad_fn

In [17]:
z = y*y*3
out = z.mean()
z

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)

In [18]:
out

tensor(27., grad_fn=<MeanBackward0>)

In [19]:
out.backward()

In [21]:
x.grad

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])

In [37]:
n = torch.randn((1,3),requires_grad=True)
m = torch.randn(3,requires_grad=True)

In [46]:
print(n.size(),m.size())
print(n.shape,m.shape)
print(n.ndim,m.ndim)
m.reshape((1,3))
m.ndim

torch.Size([1, 3]) torch.Size([3])
torch.Size([1, 3]) torch.Size([3])
2 1


1

In [64]:
torch.manual_seed(0)
print(torch.rand(1))
print(torch.rand(1))
print(torch.rand(1))
print(torch.rand(1))
print(torch.rand(1))

tensor([0.4963])
tensor([0.7682])
tensor([0.0885])
tensor([0.1320])
tensor([0.3074])


In [65]:
torch.manual_seed(1)
print(torch.rand(1))
print(torch.rand(1))
print(torch.rand(1))
print(torch.rand(1))
print(torch.rand(1))

tensor([0.7576])
tensor([0.2793])
tensor([0.4031])
tensor([0.7347])
tensor([0.0293])


In [67]:
torch.manual_seed(1)
# torch.manual_seed(2)
print(torch.rand(1))
print(torch.rand(1))
print(torch.rand(1))
print(torch.rand(1))
print(torch.rand(1))

tensor([0.7576])
tensor([0.2793])
tensor([0.4031])
tensor([0.7347])
tensor([0.0293])
